#!/bin/sh

# Build the Hume library.

echo "Generating object files..."
g++ -c *.cpp
echo "Object files generated."

echo "Creating library..."
ar rvs libhume.a *.o
echo "Finished."

echo "Moving up one level..."
mv libhume.a ../
echo "Moved libhume.a."

echo "Build finished."
exit 0
