#!/bin/sh

# Builds the Hume library.

# Get rid of previous files
echo "===== BUILDING HUME LIBRARY ====="
if test -f libhume.a
then
	echo "Found old archive. Deleting..."
	rm libhume.a
fi

echo "Generating object files..."
g++ -std=c++11 -c *.cpp
echo "Object files generated."

echo "Creating library..."
ar rvs libhume.a *.o > /dev/null

# Check for it.
if test -f libhume.a
then
	echo "Library created."
else
	echo "Library wasn't generated. Something went wrong."
fi

# Cleanup
rm *.o 3> /dev/null

exit 0
